---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apod
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - host: apod.anetwork.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: apod
                port:
                  number: 80
